include: "/ci-templates/gitlab/release-train.yml"

.staging: &staging
  rules:
    &staging-rules # For commits on the main branch, build for the staging environment
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - when: manual
  variables: &staging-variables
    ENVIRONMENT: staging
    CAPELLA_DOCKER_IMAGES_REVISION: "$CI_COMMIT_REF_NAME"
    IMAGE_BUILDER_GITLAB_REPOSITORY: "$IMAGE_BUILDER_GITLAB_REPOSITORY"
    BUILD_FOR_LATEST_TAG: "0"
    DOCKER_BUILD_ARGS: "" # Enable Docker build cache

.production: &production
  rules: &production-rules # For tags, build for the production environment
    - if: "$CI_COMMIT_TAG != null"
  variables: &production-variables
    ENVIRONMENT: production
    CAPELLA_DOCKER_IMAGES_REVISION: "$CI_COMMIT_REF_NAME"
    IMAGE_BUILDER_GITLAB_REPOSITORY: "$IMAGE_BUILDER_GITLAB_REPOSITORY"
    BUILD_FOR_LATEST_TAG: "1"

.jupyter-with-collaboration: &jupyter-with-collaboration
  JUPYTER_IMAGE_TAG_PREFIX: "with-collaboration"
  JUPYTER_ADDITIONAL_REQUIREMENTS: "jupyter-collaboration"

.jupyter-without-collaboration: &jupyter-without-collaboration
  JUPYTER_IMAGE_TAG_PREFIX: "without-collaboration"
  JUPYTER_ADDITIONAL_REQUIREMENTS: ""

production-base:
  extends: .base
  <<: *production

production-jupyter-with-collaboration:
  extends: .jupyter
  needs:
    - job: production-base
      optional: true
  rules: *production-rules
  variables:
    <<: [*production-variables, *jupyter-with-collaboration]

production-jupyter-without-collaboration:
  extends: .jupyter
  needs:
    - job: production-base
      optional: true
  rules: *production-rules
  variables:
    <<: [*production-variables, *jupyter-without-collaboration]

production-papyrus:
  extends: .papyrus
  needs:
    - job: production-base
      optional: true
  <<: *production

production-eclipse:
  extends: .eclipse
  needs:
    - job: production-base
      optional: true
  <<: *production

staging-base:
  extends: .base
  <<: *staging

staging-jupyter-with-collaboration:
  extends: .jupyter
  needs:
    - job: staging-base
      optional: true
  rules: *staging-rules
  variables:
    <<: [*production-variables, *jupyter-with-collaboration]

staging-jupyter-without-collaboration:
  extends: .jupyter
  needs:
    - job: staging-base
      optional: true
  rules: *staging-rules
  variables:
    <<: [*production-variables, *jupyter-without-collaboration]

staging-capella:
  extends: .capella
  needs:
    - job: staging-base
      optional: true
  <<: *staging

staging-papyrus:
  extends: .papyrus
  needs:
    - job: staging-base
      optional: true
  <<: *staging

staging-eclipse:
  extends: .eclipse
  needs:
    - job: staging-base
      optional: true
  <<: *staging
