version: "3"

services:
  descriptioneditor:
    # 1. run with RDP server via
    #    docker compose run -p 3390:3389 --user=root -e GIT_PASSWORD=<SET_BOT_PASSWORD> descriptioneditor
    # 2. Establish RDP client connection to techuser@localhost:3390
    # 3. docker compose exec -it descriptioneditor zsh
    #    or
    #    docker compose exec -it capella_broken_desc_editor capella -data /workspace
    image: descriptioneditor
    build:
      context: .
    container_name: descriptioneditor
    hostname: descriptioneditor
    command: /bin/zsh
    environment:
      DISPLAY: ":10"
      GIT_USERNAME: SET-Bot
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - "$HOME/repos:/home/techuser/repos"
      - "./scripts:/opt/scripts"

# docker run -p 3390:3389 -e DISPLAY=:10 --user=root \
# -e GIT_PASSWORD=iHsSza7jz53oYK3do23Y \
# --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
# -v $(realpath ./scripts):/opt/scripts \
# --name=descriptioneditor capella_broken_desc_editor
#
# docker exec --user=techuser -it descriptioneditor /opt/capella/capella -data /workspace
#
# docker exec --user=root -it -e descriptioneditor nvim -c 'cd /opt/scripts' -c 'e hello_world.py' -c 'new' -c 'terminal'
