# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: CC0-1.0
name: Push docker images to GitHub container registry

on:
  push:
    branches: [main, staging, add-image-push-workflow-to-ghcr]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main, staging]

jobs:
  deploy-docker-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        include:
          - image: ghcr.io/DSD-DBS/capella-dockerimages/base
            context: base
          - image: ghcr.io/DSD-DBS/capella-dockerimages/capella/base
            context: capella
            build-args: |
              BASE_IMAGE=ghcr.io/DSD-DBS/capella-dockerimages/base
              BUILD_TYPE=online
              CAPELLA_VERSION=5.2.0
          - image: ghcr.io/DSD-DBS/capella-dockerimages/capella/ease
            context: ease
            build-args: |
              BASE_IMAGE=ghcr.io/DSD-DBS/capella-dockerimages/capella/base
              BUILD_TYPE=online
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: ${{ matrix.build-args }}
      - name: Debug
        id: debug
        run: |
          echo ${{ steps.meta.outputs.tags }};
          echo ${{ steps.meta.outputs.json }};
