# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: CC0-1.0
name: Push docker images to GitHub container registry

on:
  push:

env:
  registry: ghcr.io/dsd-dbs/capella-dockerimages/
  images: capella/remote capella/readonly capella/ease

jobs:
  deploy-docker-images:
    runs-on: ubuntu-latest
    name: build and push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"
      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: sha
        run: echo "short=$(git rev-parse --short HEAD)" > "$GITHUB_OUTPUT"
      - name: Build
        run: make ${{ env.images }} DOCKER_PREFIX=${{ env.registry }} DOCKER_TAG=${{ steps.sha.outputs.short }}
      - name: Test readonly image
        run: |
          pip install pytest docker
          pytest tests
      - name: Push
        run: |
          for image in ${{ env.images }}
          do docker push ${{ env.registry }}$image:${{ steps.sha.outputs.short }}
          done
