# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: CC0-1.0
name: Push docker images to GitHub container registry

on:
  push:

env:
  registry: ghcr.io/dsd-dbs/capella-dockerimages/

jobs:
  deploy-docker-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        image:
          - capella/remote
          - capella/readonly
          - capella/ease
    name: build and push ${{ matrix.image }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: sha
        run: echo "short=$(git rev-parse --short HEAD)" > "$GITHUB_OUTPUT"
      - name: Build
        run: make ${{ matrix.image }} DOCKER_PREFIX=${{ env.registry }} DOCKER_TAG=${{ steps.sha.outputs.short }}
      # - name: Build and push Docker image
      #   id: build-and-push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ${{ matrix.context }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     build-args: |
      #       ${{ steps.base-image.outputs.build-arg }}
      #       ${{ matrix.build-args }}
      #     push: ${{ github.ref == 'refs/heads/main' }}
