# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: CC0-1.0
name: Build & push images

on:
  push:
  pull_request:
    branches: [main, staging]

env:
  registry: ghcr.io/dsd-dbs/capella-dockerimages/
  images: capella/remote capella/readonly capella/ease capella/cli

jobs:
  deploy-docker-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        capella_version:
          - "5.0.0"
          - "5.2.0"
          - "6.0.0"
          - "6.1.0"
        dropins:
          - name: "no" # no dropins
            dropins: ""
          - name: "selected"
            dropins: "CapellaXHTMLDocGen,DiagramStyler,Filtering,PVMT,Requirements,SubsystemTransition,TextualEditor" # selected set of dropins
          - name: "all"
            dropins: "CapellaXHTMLDocGen,DiagramStyler,Filtering,PVMT,Requirements,SubsystemTransition,TextualEditor" # all open source dropins
    name: Capella ${{ matrix.capella_version }} with ${{ matrix.dropins.name }} dropins
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          cache: pip
          cache-dependency-path: ./pyproject.toml
          python-version: "3.11"
      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: tag
        run: |
          echo "branch=$(git rev-parse --abbrev-ref HEAD | sed 's/[^a-zA-Z0-9]/-/g')" >> "$GITHUB_OUTPUT"
          echo "sha=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: Build
        run: >
          make ${{ env.images }}
          CAPELLA_VERSIONS="${{ matrix.capella_version }}"
          DOCKER_PREFIX="${{ env.registry }}"
          CAPELLA_DOCKERIMAGES_REVISION="${{ steps.tag.outputs.branch }}"
          CAPELLA_DROPINS="${{ matrix.dropins.dropins }}"
          DOCKER_TAG_SCHEMA='${CAPELLA_VERSION}'-${{ matrix.dropins.name }}-'${CAPELLA_DOCKERIMAGES_REVISION}'
          DOCKER_BUILD_FLAGS="--label git-short-sha=${{ steps.tag.outputs.sha }}"
      - name: Install test dependencies
        run: |
          pip install .
      - name: Run pytest
        run: >
          DOCKER_PREFIX="${{ env.registry }}"
          DOCKER_TAG="${{ matrix.capella_version }}-${{ steps.tag.outputs.branch }}"
          pytest -m "not (t4c_server or t4c)" tests
      - name: Push
        run: |
          for image in ${{ env.images }}
          do docker push "${{ env.registry }}$image:${{ matrix.capella_version }}-${{ steps.tag.outputs.branch }}"
          done
