# SPDX-FileCopyrightText: Copyright DB Netz AG and the capella-collab-manager contributors
# SPDX-License-Identifier: CC0-1.0
name: Push docker images to GitHub container registry

on:
  push:

env:
  registry: ghcr.io/dsd-dbs/capella-dockerimages/
  images: capella/remote capella/readonly capella/ease capella/cli

jobs:
  deploy-docker-images:
    runs-on: ubuntu-latest
    strategy:
     matrix:
       capella_version:
         - "5.0.0"
         - "5.2.0"
         - "6.0.0"
    name: Build image for Capella ${{ matrix.capella_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"
      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: tag
        run: echo "branch=$(git rev-parse --abbrev-ref HEAD)" > "$GITHUB_OUTPUT"
      - name: Build
        run: make ${{ env.images }} CAPELLA_VERSION=${{ matrix.capella_version }} DOCKER_PREFIX=${{ env.registry }} CAPELLA_DOCKERIMAGES_REVISION=${{ steps.tag.outputs.branch }}
      - name: Test readonly image
        run: |
          pip install pytest docker
          DOCKER_CAPELLA_READONLY="${{ env.registry }}capella/readonly:${{ steps.tag.outputs.branch }}" pytest tests
      - name: Push
        run: |
          for image in ${{ env.images }}
          do docker push ${{ env.registry }}$image:${{ steps.tag.outputs.branch }}
          done
